// Lab 5 Testbench: Synchronous Block RAM (BRAM) S-Box Verification
`timescale 1 ns / 1 ps

module tb_blk_mem_gen_0();

    reg        tb_clk;
    reg  [3:0] tb_adrs;
    wire [3:0] tb_data;

    // Fixed warning flags (Inputs to the BRAM IP typically tied to constant values for ROM behavior)
    wire ena = 1'b1;
    wire [0:0] wea = 1'b0; // Write Enable is 0 for Read-Only Memory
    wire [3:0] dina = 4'd0;

    // Clock Generation (100MHz equivalent)
    always #50 tb_clk = ~tb_clk;

    initial begin
        $display("Time\t Address\t Data_Out");
        $monitor("%4g\t %h\t\t %h", $time, tb_adrs, tb_data);
    end

    initial begin
        // Initialization
        tb_clk = 1'b1;
        
        // Stimulus - Notice the outputs will be delayed by 1 clock cycle due to BRAM latency
        #100 tb_adrs = 4'd0;
        #100 tb_adrs = 4'd1;
        #100 tb_adrs = 4'd2;
        #100 tb_adrs = 4'd3;
        #100 tb_adrs = 4'd4;
        #100 tb_adrs = 4'd5;
        #100 tb_adrs = 4'd6;
        #100 tb_adrs = 4'd7;
        #100 tb_adrs = 4'd8;
        #100 tb_adrs = 4'd9;
        #100 tb_adrs = 4'd10;
        #100 tb_adrs = 4'd11;
        #100 tb_adrs = 4'd12;
        #100 tb_adrs = 4'd13;
        #100 tb_adrs = 4'd14;
        #100 tb_adrs = 4'd15;
        #100 $finish;
    end

    // Xilinx Block Memory Generator IP Instantiation
    // Note: The module name is auto-generated by Vivado IP Catalog
    decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix dut (
        .clka(tb_clk),
        .addra(tb_adrs),
        .douta(tb_data),
        .ena(ena),
        .wea(wea),
        .dina(dina)
    );

endmodule
